### ISSUE TITLE
[Feature] Non-empty directory and file check

### ISSUE THREAD

**Issue by BorisovskiP** [CaptainHookPhp/captainhook#101]
We have created custom hooks that check if a give file or a given directory is empty.

The `checkFile` hook we have differs a bit from https://github.com/CaptainHookPhp/captainhook/blob/63627ba9b1140674164ea66619ee1225555edaca/src/Hook/File/Action/IsEmpty.php since we open the file and check for its contents and make sure that its not an empty file. 

We also have a `CheckFolder` hook that checks a given folder if its empty or not. Could this be something that could be implemented as a core feature? If so, we are willing to open a PR for this.

If not, we would submit these features as a custom module/plugin in https://captainhookphp.github.io/captainhook/extend.html#plugins

**Comment by sebastianfeldmann** [comment]
Hi, sure as long as Hooks do not need new dependencies and they kind of do things that others are likely to use as well I'm happy to include them into the Cap'n directly.

Speaking about an `Directory::isEmpty` hook, you have to remember, even if the directory is not empty it does not mean that any of its content is committed to git, you always have to check the index (staged files).

I think I would most likely change the `File::isEmpty` hook in a way it accepts wildcards like `logs/*` or something. So it makes sure you only commit files without content to the `logs` directory.

We could then add an action like `File\Action\NotAllowed` that even isn't allows empty files but does not accept configured files in a commit at all. 

```
{
    "action": "\\CaptainHook\\App\\Hook\\File\\Action\\IsEmpty",
    "options": {
         "files": [
             "config.overwrite.local"
         ]
    }
},
{
    "action": "\\CaptainHook\\App\\Hook\\File\\Action\\NotAllowed",
    "options": {
         "files": [
             "log/*"
         ]
    }
}
```

So this would allow you to commit config.overwrite.local if somebody accidentally commit contents in there, but you are not allowed to commit any log files.

**Comment by BorisovskiP** [comment]
I'm sorry i did not explain it correctly. We have two actions: `CheckFile` and `CheckFolder`.
Both of these actions have two options: 
```
"options": {
     "pathSrc": "/src/*/*/",
     "fileName": "README.md"
               }
```
```
"options": {
      "pathSrc": "/src/*/*/",
      "folderName": "Test"
                 }

```
The `CheckFile` action gets the `fileName` that is defined in `captainhook.json`. Our initial use for this is to check if a `README.md` file exists in a given path. Here we firstly check if this file exists, and if it does we get the contents of that file and make sure that its not empty.

The `CheckFolder` action get the `folderName` that is defined in `captainhook.json`. We search for a folder named `Test` in a given path. We then check if this folder exists and if it does, we also check that its not empty as in we expect to have some tests present in the Test folder.

These hooks were developed as a module for Magento, where before we commit a change, we would like to check if a `README.md` exists or the `Test` folder is present and not empty. There are of course not limited only to Magento and can be modified or extended to check for any other folder/path.

**Comment by sebastianfeldmann** [comment]
Ah now I get it. You are checking the "reverse".

So I think actions like this are what you want to add right?

`CaptainHook\App\Hook\File\Action\NotEmpty`
`CaptainHook\App\Hook\Directory\Action\NotEmpty`

**Comment by BorisovskiP** [comment]
Yes

**Comment by sebastianfeldmann** [comment]
Love it :)

**Comment by sebastianfeldmann** [comment]
This feature got released with version 5.4.1

### IsEmpty

The following will make sure you do not commit any log file with contents to the repository.
Files are only checked if they are included in the current commit. So you can commit even if your log files are not empty as long as you do not include such log files in your commit.

```
"pre-commit": {
  "enabled": true,
  "actions": [
    {
      "action": "\\CaptainHook\\App\\Hook\\File\\Action\\IsEmpty",
      "options": {
        "files": [
          "logs/*.log"
        ]
      },
      "conditions": []
    }
  ]
}
```

### IsNotEmpty

To make sure you do not commit empty files you can configure something like this.
This will make sure you can not commit empty `README.md` files. Again, this will allow you to commit while having empty `README.md` files as long as you do not include them in your current commit.

```
"pre-commit": {
  "enabled": true,
  "actions": [
    {
      "action": "\\CaptainHook\\App\\Hook\\File\\Action\\IsNotEmpty",
      "options": {
        "files": [
          "src/Modules/**/README.md"
        ]
      },
      "conditions": []
    }
  ]
}
```

**Comment by BorisovskiP** [comment]
@sebastianfeldmann Will `CaptainHook\App\Hook\Directory\Action\NotEmpty` be  implemented in a future release?

**Comment by sebastianfeldmann** [comment]
The thing is that I changed the implementation of `IsEmpty` that is part of `CaptainHook` a bit.

The final implementation of `IsEmpty` is only checking files that are included in the commit.
So you can commit even if you have log files that are not empty as long as you do not commit those log files.

That leads to a problem with empty directories because you can not commit empty directories into a git repository.
So checking for empty directories does not make sense.
If you want to make sure you do not commit files in a directory you should use an entry in your `.gitignore` file.

**Comment by sprankhub** [comment]
Well you could commit an "almost-empty" directory when you add a `.keep` / `.gitkeep` file to it :-)

However, I think you misread the action @BorisovskiP mentioned. He wants to have a `NotEmpty` check for directories. I think `.gitignore` does not help here.

I think it is important to share the actual use case: We develop Magento modules and all tests need to reside in the `Test` directory. Hence, we would like to have a check, which makes sure that every module has a not-empty `Test` directory. This can of course easily be circumvented, but still, it is a basic check to see if tests have been implemented. Do you see this as a valid use case? Do you have other ideas to implement such a check, @sebastianfeldmann?

**Comment by sebastianfeldmann** [comment]
🤔

This would make sense as a `pre-push` hook, so you are allowed to commit and do stuff, but you are not allowed to push as long as you have not committed some files in a configured directory.

This would mean that you would have to run a git command like this

    git ls-files tests/*

to make sure there are actually "files" stored in the repository.

Quite a while ago I created repositories like `captainhook/hooks-magento` and other "frameworks". Maybe this would be a perfekt use case for Magento specific rules and actually bringing this repository to life.

**Comment by sprankhub** [comment]
So you do not see a general use case for this? So there will not be a `Directory\NotEmpty` check or something similar in the CaptainHook core? I still think this can be applied to other frameworks as well...

**Comment by sebastianfeldmann** [comment]
🤔 if I think about it I'm only unhappy with the naming `Directory\NotEmpty`.

If we come up with an alternative like `EnsureFilesExist` with a configuration like `tests/**/*Test.php`.
I think that would be totally usable for a lot of people.

**Comment by sprankhub** [comment]
Looking at the currently implemented hooks in [`CaptainHook\App\Hook\File\Action`](https://github.com/CaptainHookPhp/captainhook/tree/0816b79df9539611c2fa1d455a4f15bad233eed8/src/Hook/File/Action), I would then suggest another hook `CaptainHook\App\Hook\File\Action\Exists`, which allows for something like this:

    "pre-commit": {
      "enabled": true,
      "actions": [
        {
          "action": "\\CaptainHook\\App\\Hook\\File\\Action\\Exists",
          "options": {
            "files": [
              "tests/**/*Test.php"
            ]
          },
          "conditions": []
        }
      ]
    }

What do you think, @sebastianfeldmann?

**Comment by sebastianfeldmann** [comment]
Looks good to me 👍

**Comment by sebastianfeldmann** [comment]
I already add the functionality to the `Repository` implementation. If you update `sebastianfeldmann/git` to the latest version you will be able to check for files in the repository.

https://github.com/sebastianfeldmann/git/blob/b6ca1859f9a9c6eb77f0981fc9cb69ce7494542c/src/Operator/Info.php#L120-L137


```
$listOfFiles = $repository->getInfoOperator()->getFilesInTree('tests/**/*Test.php');
```

**Comment by sprankhub** [comment]
Nice! Then this should not be too hard to do I guess. Would you prefer a PR for this or would you like to implement this yourself?

**Comment by sebastianfeldmann** [comment]
If you want to you can open a PR but if you prefer me doing the implementation for whatever reason I can do this as well.
Most likely later next week.

**Comment by sprankhub** [comment]
To be honest, I would not be able to do it earlier than this, so if you are fine with it, I am very thankful if you implement it :-)

Maybe we should re-open this until then?

Thanks a lot in any case, @sebastianfeldmann!

**Comment by sebastianfeldmann** [comment]
So I will take care of it ;)

**Comment by sebastianfeldmann** [comment]
Version 5.4.3 includes now this `Exists` action.

https://github.com/CaptainHookPhp/captainhook/blob/b5cd61789054379a57a0b5f85477ae490244a38e/src/Hook/File/Action/Exists.php#L20-L41
