### ISSUE TITLE
[Feature] Conventional Commits Action for Commit linting

### ISSUE THREAD

**Issue by lukaszgoworko** [captainhookphp/captainhook#112]
# Problem
I'm using [Conventional Commits 1.0.0](https://www.conventionalcommits.org/en/v1.0.0/) for my commit messages. It alows me to auto generate changelog and tags. I'm also using the [commitizen-cli](https://github.com/commitizen/cz-cli) tool to generate this commit messages.

To lint the messages with captainhook I needed a regex and some rules. It would be easier to have a nice Action:

**I would contribute too, please contact me if you are interested.**

## My current solution
This is the actions in my config:
``` json
    "commit-msg": {
        "enabled": true,
        "actions": [
            {
                "action": "\\CaptainHook\\App\\Hook\\Message\\Action\\Rules",
                "options": [
                    [
                        "\\CaptainHook\\App\\Hook\\Message\\Rule\\LimitSubjectLength",
                        [100]
                    ],
                    [
                        "\\CaptainHook\\App\\Hook\\Message\\Rule\\LimitBodyLineLength",
                        [100]
                    ]
                ]
            },
            {
                "action": "\\CaptainHook\\App\\Hook\\Message\\Action\\Regex",
                "options": {
                    "regex": "/^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\\(.+\\))?: (.+)(\\R{2}(.+\\R?)*)?(\\R{2}(BREAKING CHANGE: .*))?(\\R{2}([A-Z]+-[0-9]+))?$/m"
                },
                "conditions": []
            }
        ]
    }
```

The Regex is specified for JIRA Task Issues (TEST-92). This should be generalized first or there can be an option for that. Also I saw already that your message Class can distinguish already between content and body. The footer could be introduced too.

**Comment by shochdoerfer** [comment]
There is already a plugin that handles conventional commits, see here https://github.com/ramsey/conventional-commits

Does that handle all your needs?

**Comment by lukaszgoworko** [comment]
@shochdoerfer will try that out. Thanks a lot!
