### ISSUE TITLE
Allow filtering the files/directories to check

### ISSUE THREAD

**Issue by juho-jaakkola** [captainhookphp/captainhook#114]
I'm working on a code base, where the code is split into legacy code and new code. I would like the hooks to be run only for the new code. In my use case it would be enough to filter by the directory where the new code lives.

However, I have not found a way to filter out specific files or directories when running a hook like this:

```
php-cs-fixer {$STAGED_FILES|of-type:php}
```

Any ideas, how this could be possible?

I wonder if it would make sense to add a new configuration entry (i.e. array of target directories), and then use that as an additional filter in `\CaptainHook\App\Runner\Action\Cli\Command\Formatter`.

**Comment by juho-jaakkola** [comment]
Or maybe it would make sense to have a blacklist instead of whitelist.

**Comment by sebastianfeldmann** [comment]
In your case I would create a `phpcs` configuration and call PHPCodesniffer without any arguments.
This way you will not the speed benefit from only running changed files but you have full control on what is getting tested and what is not.

**Comment by marcelthole** [comment]
maybe i have a new use case for this use case.
I use a mono repository and want to run some checks only if the files in the specific folder has staged changes.
in this case i can't use the existing FileStaged Conditions and would like to add a new `InDirectory` Condition.

**Comment by sebastianfeldmann** [comment]
There now is a condition that checks if files in a given directory will be committed `v5.6.1`

```
"action": "some-action"
 "conditions": [
   {"exec": "\\CaptainHook\\App\\Hook\\Condition\\FileStaged\\InDirectory",
    "args": [
      "src/"
   ]}
 ]
```

Be aware that conditions are currently combined with `OR`
We are working on a solution for this but it will take a little bit more time.
