### ISSUE TITLE
Git hooks should use correct PHP version

### ISSUE THREAD

**Issue by iherak** [captainhookphp/captainhook#117]
# Use case
In the use case where one has multiple PHP versions installed locally, and each project uses it's own version, captainhook gets called with the "wrong" PHP executable.
The problem here is that captainhook writes a shell call to git hooks with something like this:
```
vendor/captainhook/captainhook/bin/captainhook $INTERACTIVE --configuration=captainhook.json --bootstrap=vendor/autoload.php hook:pre-commit "$@" <&0
```

This is a problem - because this makes it use default php version, and not the one that should be used in the project.

# Proposed solution(s)
As composer is always called with a proper php version, I suggest using `Symfony\Component\Process\PhpExecutableFinder` to find currently used PHP version in the shell template (`src/Hook/Template/Local/Shell.php`). Let me know if this looks good to you, and if you'd like me to create a PR with this fix.
With the proposed fix git hooks now look something like this:
```
/usr/bin/php7.4 vendor/captainhook/captainhook/bin/captainhook $INTERACTIVE --configuration=captainhook.json --bootstrap=vendor/autoload.php hook:pre-commit "$@" <&0
```

Alternatively, we could add config for path to the php executable:
```
"config": {
        "php-path": "/usr/bin/php7.4"
    },
```
Such config would then be passed from `CaptainHook\App\Hook\Template\Builder` to the template `CaptainHook\App\Hook\Template\Local`, and used same as above in `src/Hook/Template/Local/Shell.php` to set the git hooks to use proper PHP.

You can check WIP of both solutions on the fork:
1. https://github.com/iherak/captainhook/commit/2884de75c72b9fa32c08812eb27c2bca1ff7578e
2. https://github.com/iherak/captainhook/commit/2b066c6ca033c0f71ad71c3e1b8dc6c5a5658866

Also, let me know if I missed something obvious - but I have failed to find any kind of config which could be used instead of this fix.

**Comment by sebastianfeldmann** [comment]
Thanks @iherak for putting in the effort.

I would totally prefer the config solution over the php executional finder.
The only thing you have to account for is that by default the `php-path` value is empty and that it should still work exactly the same without a value.

**Comment by iherak** [comment]
Great, I'll start on a complete solution and provide a PR soon I hope.
