### ISSUE TITLE
Seperate Plugin API Repository

### ISSUE THREAD

**Issue by marcelthole** [captainhookphp/captainhook#129]
hey,

with the new phar only variant it's not possible to create custom Actions, because the `\CaptainHook\App\Hook\Action` Interface is not available.

It would be awesome if a "simple" PluginRepository could be created with the interfaces only.

Or is there a other way to run custom actions with custom args?

**Comment by sebastianfeldmann** [comment]
This is only an issue for the autocompletion in your IDE.
If you execute the PHAR the interface is loaded and you will not run into any errors
