### ISSUE TITLE
post-change Hook With Disabled post-merge / post-checkout Hooks

### ISSUE THREAD

**Issue by sprankhub** [captainhookphp/captainhook#131]
It looks like the virtual `post-change` hook is only executed if the triggering `post-merge` / `post-checkout` hooks are enabled. It feels weird to have them enabled, although they have no actions. My current configuration looks like this:

    {
        "post-merge": {
            "enabled": true,
            "actions": []
        },
        "post-checkout": {
            "enabled": true,
            "actions": []
        },
        "post-change": {
            "enabled": true,
            "actions": [
                {
                    "action": "echo test",
                    "options": []
                },
            ]
        }
    }

This works. However, as soon as I set `post-merge` / `post-checkout` to disabled (which would make sense as they do not have any actions), it does not work any more.

Do you see a proper way to make this more intuitive, @sebastianfeldmann?

Thanks!

**Comment by sebastianfeldmann** [comment]
Thats's good to know!
I will have a look and most likely fix it in a way so the "virtual" hooks are executed even if no "real" hooks are configured.

**Comment by sebastianfeldmann** [comment]
I just release version 5.8.1 that should fix the issue.
Thanks for reporting it :)

**Comment by sprankhub** [comment]
Thanks @sebastianfeldmann!
