### ISSUE TITLE
Please remove or provide option to disable ASCII parrot

### ISSUE THREAD

**Issue by NamelessCoder** [captainhookphp/captainhook#133]
While it might seem fun at first, the 100th time you're confronted with an ASCII parrot that wastes 15 lines of console output just to say "Avast!" it stops being funny (in particular for git guis that render this output in a limited feedback window). Please either remove this or provide a global option to disable that part of the error output.

**Comment by sebastianfeldmann** [comment]
Over the last couple of days I removed a ton of useless output including the once beloved parrot :)

I will run some final tests and release a new version if everything works and look "good".

**Comment by NamelessCoder** [comment]
Thanks Sebastian! I'll look forward to this when we update the dependency next time :)
