### ISSUE TITLE
Configuration to set the PHP bin path

### ISSUE THREAD

**Issue by thomas-kl1** [captainhookphp/captainhook#136]
Hi, it would be great to have the capability to set the PHP bin path. I can help to implement this :)

The php bin is not always global or could be different (like prefixed with version, such as php74 or php80...)

**Comment by thomas-kl1** [comment]
Hi @sebastianfeldmann thanks for the info. However it looks like the PHP Lint has the `php` command hardcoded https://github.com/captainhookphp/captainhook/blob/main/src/Hook/PHP/Action/Linting.php#L77

Also it looks like that the captainhook composer plugin is not aware of the running php for composer:

E.g: php80 composer.phar update => trigger run captainhook with php (which is an other version of does not exists)

I have tried to add extra captainhook exec in my root composer.json, without success because I can't suffix the command path with the proper php path

I'm not sure if I'm actually clear 😆

**Comment by sebastianfeldmann** [comment]
You are absolutely right about the `Linting` action. That should be an easy fix with `$config->getPhpPath()`

Similar with the composer plugin, I have to check if there is a way to determine the used php binary to execute Composer.
Would 100% make sense to use the same binary to execute the Cap'n

**Comment by sebastianfeldmann** [comment]
I updated the composer plugin to version 5.3.1 from now on it will use the same PHP binary that was used to execute Composer.

I fixed the `Linting` action as well and released version 5.10.1
Hope that solves all your issues :)

If you still run into problems just reopen the issue :)

**Comment by thomas-kl1** [comment]
You rock @sebastianfeldmann !! It works like a charm :)

I wasn't aware of `PHP_BINARY`, PHP is so helpful and we don't even know it! Thank you for your amazing work!

**Comment by sebastianfeldmann** [comment]
I wasn't either :)
Had to check the docs to find this little gem.

Thanks for your kind words, super happy it works. Thanks for using the Cap'n and giving feedback  :)

**Comment by alfredbez** [comment]
> You can use it in actions like this.
> 
> ```
> ...
>   "action": "{$CONFIG:value-of|php-path} tools/phpcs --standard=psr12"
> ...
> ```

Just in case someone stumbles upon this: It should be `$CONFIG|value-of:php-path` instead of `$CONFIG:value-of|php-path` I think.
```diff
-$CONFIG:value-of|php-path
+$CONFIG|value-of:php-path
```
Should look like this in the end:
```
"action": "{$CONFIG|value-of:php-path} tools/phpcs --standard=psr12"
```
[See also](https://regex101.com/r/fjq1vy/1)

----

Is this already documented somewhere besides this GH issue?

**Comment by sebastianfeldmann** [comment]
Good Question, I will go and check und update the docs if necessary :)
