### ISSUE TITLE
[question] Running hooks on Windows

### ISSUE THREAD

**Issue by Menelion** [captainhookphp/captainhook#141]
For some reason I cannot run my actions in a pre-commit hook on Windows. I'm getting `psalm is not an internal or external command, operable program or batch file`.

What is the correct way of indicating paths in the config JSON file so they would be recognized by Windows as well as by Linux? I have standard repository layout, with `vendor/bin/(psalm, phpunit, captainhook etc.)`.

**Comment by sebastianfeldmann** [comment]
Normally `vendor/bin/phpunit` should work.

If it does not you can try `php vendor/bin/phpunit`.

Make sure at least `php` is in your PATH.

**Comment by Menelion** [comment]
Thanks, `php vendor/bin/phpunit` worked like a charm :).
