### ISSUE TITLE
Language: Imperative mood

### ISSUE THREAD

**Issue by Lewiscowles1986** [captainhookphp/captainhook#142]
Ben from Ramsey/UUID is giving a talk where I saw the text "Subject should be written in imperative mood". 

I'm a native English speaker. I Had to ask what that meant.

Would you be open to a PR to change this. Two ideas for improvements I have had are:

- Change text to `Subject should read as a succinct command.`
- Provide example prefixed with `Example: Improves tests for ImportSelector`

**Comment by sebastianfeldmann** [comment]
As a reminder a commit message should always complete the following sentence.

This commit will [YOUR COMMIT MESSAGE].

Maybe we could use this somehow.

**Comment by Lewiscowles1986** [comment]
Even that us much clearer than:

> "Subject should be written in imperative mood"

Using that would be perfect.

What do you think of:

> Subject line should complete the sentence `This commit will [YOUR COMMIT MESSAGE].`

**Comment by Lewiscowles1986** [comment]
Is the reason for that language, a desire to keep the message succinct for the reader?

**Comment by sebastianfeldmann** [comment]
The think the idea behind that language is to tell other users what happens if they merge changes and to remember programmers that they write commit messages for an audience.

The think the "imperative" stuff is just convention and a way to keep your subjects short, succinct, precise or how ever you want to call it :)

**Comment by Lewiscowles1986** [comment]
Hi, I thought I'd let this sit as we both seem to be missing each other and I needed to try to explain this:

* Imperative mood is not the issue I was raising, the phrasing is. It's confusing. The words imperative mood, don't mean a lot to a lot of English speakers.
* What I was asking about was providing an example, or changing the sentence.

> As a reminder a commit message should always complete the following sentence.
> This commit will [YOUR COMMIT MESSAGE].

This was perfect. It was simple, clearer. I'm sorry I tried to iterate on it.

Would you be open to a PR to change the language to fit that; or is there a way to customize the messages for picky people? 😄

**Comment by sebastianfeldmann** [comment]
No don't worry I totally got your point.

I change the `hint` providing the error message :)

Should be included in the next release.
Thanks a lot for the feedback. As someone who speaks English as a foreign language I am always grateful for such hints :)
