### ISSUE TITLE
Multiple placeholders with options are combined

### ISSUE THREAD

**Issue by ComiR** [captainhookphp/captainhook#143]
I wanted to filter the `STAGED_FILES` by multiple directories (or), but since `{$STAGED_FILES|in-dir:dirA,dirB}` is not possible I tried `{$STAGED_FILES|in-dir:dirA} {$STAGED_FILES|in-dir:dirB}`. This resulted in a buggy behaviour: only files from "dirB" were printed.

I could trace it to this regex:
https://github.com/captainhookphp/captainhook/blob/c7dbffe7519f0fdc99f0c2af828775391ede1797/src/Runner/Action/Cli/Command/Formatter.php#L107
The problem is that regex is greedy by default, which resulted in the match "STAGED_FILES\|in-dir:dirA} {$STAGED_FILES\|in-dir:dirB".
There are multiple ways of solving this issue. I suggest to simply switch the `.` with `[^}]` (add `\n` if those should be treated as before, because `.` = `[^\n]`).

**Comment by sebastianfeldmann** [comment]
I just added the `U` modifier to make the regex not greedy.

I will release a new version with this fix ASAP :)

**Comment by sebastianfeldmann** [comment]
This should be fixed in version `5.10.2`

If you still ru into troubles feel free to reopen this issue or open a new one ;)
