### ISSUE TITLE
File Staged Condition - Multiple Types

### ISSUE THREAD

**Issue by sprankhub** [captainhookphp/captainhook#146]
We have the following hook configured:

    {
        "action": "vendor/bin/phpcs ...",
        "options": [],
        "conditions": [
            {
                "exec": "\\CaptainHook\\App\\Hook\\Condition\\FileStaged\\OfType",
                "args": [
                    "php"
                ]
            }
        ]
    }

However, I want this hook to be executed when `php` **or** `phtml` files are staged. If I understand the condition code correctly, this is currently not possible. If I understand correctly, this can currently only be implemented with two actions, which pretty much do the same. That is why I would prefer having only one action with a combined condition.

What do you think @sebastianfeldmann?

**Comment by sebastianfeldmann** [comment]
There are `AND` and `OR` conditions to combine multiple conditions together.

```json
"conditions": [{
    "exec": "and",
    "args": [
        {
            "exec": "\\CaptainHook\\App\\Hook\\Condition\\AnyFileChanged",
            "args": [["foo.php", "bar.php"]]
        },
        {
            "exec": "\\CaptainHook\\App\\Hook\\Condition\\AnyFileChanged",
            "args": [["foo.xml", "bar.xml"]]
        }
    ]
}
```

**Comment by sprankhub** [comment]
Ahh thanks, good to know! So in my case, the following should work, right?

    "conditions": [
        {
            "exec": "or",
            "args": [
                {
                    "exec": "\\CaptainHook\\App\\Hook\\Condition\\FileStaged\\OfType",
                    "args": [
                        "php"
                    ]
                },
                {
                    "exec": "\\CaptainHook\\App\\Hook\\Condition\\FileStaged\\OfType",
                    "args": [
                        "phtml"
                    ]
                }
            ]
        }
    ]

I got tricked by the following on http://captainhook.info/configure.html:

> Only if all configured conditions apply the action gets executed.

This sounds pretty strict to me. Maybe there and at http://captainhook.info/conditions.html, the possibility to define `or` conditions should be mentioned?

**Comment by sebastianfeldmann** [comment]
Yes you are right the `LogicConditions` aren't documented yet properly.

I leave this issue open as an reminder to do that ;)

**Comment by sebastianfeldmann** [comment]
I updated the documentation to promote the availability of those logic conditions a bit more.

You can find some examples here:
http://captainhook.info/conditions.html#logic-or
