### ISSUE TITLE
Hook failure due to unwanted php execution

### ISSUE THREAD

**Issue by DorianBourcet** [captainhookphp/captainhook#155]
Hi there,

I'm trying to configure CaptainHook in a PHP project.

The issue I have is that even if the the actions execute successfully, the hook never succeeds, due to an unwanted cli php execution.

Check below with a pre-commit hook.

This is the `pre-commit` configuration in my captainhook.json:
```
    {
        "enabled": true,
        "actions": [
            {
                "action": "src/vendor/bin/phpstan analyse -c src/phpstan.neon --memory-limit 1G",
                "options": [],
                "conditions": []
            }
        ]
    }
```

And the `pre-commit` file that has been set in `.git/hooks` by CaptainHook:
```
#!/bin/sh

# installed by CaptainHook 5.10.4

docker run --rm -v $(pwd):/var/www/html docker.gitlab.libeo.com/docker/php:7.4-fpm src/vendor/bin/captainhook hook:pre-commit --configuration='src/captainhook.json' "$@"
```

When I commit my code to test the hook:
```
pre-commit: 
 - src/vendor/bin/phpstan analyse -c src/phpstan.neon --memory-li... : done
Usage: php [-n] [-e] [-h] [-i] [-m] [-v] [-t] [-p <prefix>] [-g <pid>] [-c <file>] [-d foo[=bar]] [-y <file>] [-D] [-F [-O]]
  -c <path>|<file> Look for php.ini file in this directory
  -n               No php.ini file will be used
  -d foo[=bar]     Define INI entry foo with value 'bar'
  -e               Generate extended information for debugger/profiler
  -h               This help
  -i               PHP information
  -m               Show compiled in modules
  -v               Version number
  -p, --prefix <dir>
                   Specify alternative prefix path to FastCGI process manager (default: /usr/local).
  -g, --pid <file>
                   Specify the PID file location.
  -y, --fpm-config <file>
                   Specify alternative path to FastCGI process manager config file.
  -t, --test       Test FPM configuration and exit
  -D, --daemonize  force to run in background, and ignore daemonize option from config file
  -F, --nodaemonize
                   force to stay in foreground, and ignore daemonize option from config file
  -O, --force-stderr
                   force output to stderr in nodaemonize even if stderr is not a TTY
  -R, --allow-to-run-as-root
                   Allow pool to run as root (disabled by default)
```

As you can see, after the actions have been executed, something seems to execute a `php` command with wrong arguments, which causes `Usage: php [-n]`... I noticed that this is only happening when the `.git/hooks/pre-commit` gets executed through git.

I'm running macOS 12.0.1.

Any help would be appreciated.

Thank you in advance!

**Comment by sebastianfeldmann** [comment]
It looks like you `phpstan` execution does not work properly it prints out the usage information instead of running the command.

This usually happens if you mistype options in the `phpstan` command. 

I can't see any obvious errors on first glance but make sure this command works even in your docker container.
Maybe try to remove the memory limit.

**Comment by sebastianfeldmann** [comment]
The important thing ist that it works now :)
