### ISSUE TITLE
PreserveWorkingTree not restoring state if an action fails

### ISSUE THREAD

**Issue by CircleCode** [captainhookphp/captainhook#170]
in `Runner/Hook.php`, we can see that `\CaptainHook\App\Runner\Hook::afterHook` is only run if `\CaptainHook\App\Runner\Hook::executeActions` does not triggers an exception.

But if, for any reason, one of the actions fails, `\CaptainHook\App\Runner\Hook::executeActions` triggers an exception from `\CaptainHook\App\Runner\Hook::handleAction`.

it seems that in `Runner/Hook.php`, everything between `$this->beforeHook();` and `$this->afterHook();` shoud be wrapped inside a try / catch block to ensure that if `beforeHook` has been called, `afterHook` is always called.

**Comment by sebastianfeldmann** [comment]
Do you want to provide a pull request for this or should I go ahead and fix it?

**Comment by CircleCode** [comment]
I was about to provide a PR, but I realized I am not familiar enough with the way you handle errors management across the project, and this is a topic that requires homogeneity across the project.
If you have the bandwidth to handle it, I think it would be better for this one.
Is it okay on your side, or do you need me to provide a PR anyway?

**Comment by sebastianfeldmann** [comment]
Sure, I will provide a fix ASAP :)

**Comment by CircleCode** [comment]
If I ever had suspected a simple finally would have been enough, I would have done the PR :|
Not asking for ETA, I simply wondered if you plan to push a new release with this fix or if you wait for some others before releasing (in which case I could always use the current master, so no pressure on your side!)

**Comment by sebastianfeldmann** [comment]
No worries, wasn't sure to that it would be enough either, but it turns out be be just that :)

Release of 5.10.7 out including the fix ;)

**Comment by CircleCode** [comment]
Awesome, thanks for this quick fix
