### ISSUE TITLE
Can't use `Hooks::POST_CHANGE` as condition's restriction

### ISSUE THREAD

**Issue by Wirone** [captainhookphp/captainhook#171]
Today I wanted to implement simple action for refreshing cache, but skip it for file-checkouts (e.g. rollback for file performed in PHPStorm). Unfortunately, I could not restrict condition to `Hooks::POST_CHANGE` because it wasn't evaluated and action was always executed. I had to explicitly define all 3 actions that trigger virtual hook `post-change`.

```php
class ModifiesRuntime implements Condition, Constrained
{
    public function isTrue(IO $io, Repository $repository): bool
    {
        // ...
    }

    public static function getRestriction(): Restriction
    {
        // Hooks::POST_CHANGE does not work here, action is always executed
        return Restriction::fromArray([Hooks::POST_CHECKOUT, Hooks::POST_MERGE, Hooks::POST_REWRITE]);
    }
}
```

I think it should be possible to use virtual hook for restrictions.

**Comment by sebastianfeldmann** [comment]
With the next release you will be able to use virtual hooks in `Restrictions`.

Thanks for reporting this :)
