### ISSUE TITLE
Allow specifying multiple hooks that will be limited during install command

### ISSUE THREAD

**Issue by alexandrmazur96** [captainhookphp/captainhook#203]
Currently, only one hook per `install` command can be installed.

So we need to specify multiple lines in our composer scripts. Something like:

```json
{
   "scripts": {
        "build-dev": [
            "@php vendor/bin/captainhook install -f -s pre-push",
            "@php vendor/bin/captainhook install -f -s pre-commit"
        ]
    }
}
```

This process can be optimized if we allow specifying multiple hooks to install via comma, for example.

**Comment by sebastianfeldmann** [comment]
Fixed in `5.15.3` (released 5min ago)
