### ISSUE TITLE
[feature] condition about changed files at pre-push

### ISSUE THREAD

**Issue by CircleCode** [captainhookphp/captainhook#205]
as companion of #202, you may want to run your full phpunit test suite on pre-push, but only if a php file has been updated, and your full karma test suite, but only if a js file has been updated.

However, there is no such condition on pre-push.

I will first write a custom condition on my end, and I can open a merge request if you find it interesting.

**Comment by sebastianfeldmann** [comment]
There are the `Conditions` located under `CaptainHook\App\Hook\Condition\FileChanged\*` they are suited to use for `pre-push`

**Comment by CircleCode** [comment]
before working on documentation, I am a bit confused about the way the before-push hook works:

If the pushed reference is not the current HEAD (or if we push several references), the condition `FileChanged\OfType` is evaluated against pushed reference(s), but the hook is then run against the working directory. I find this surprising because I would expect the before-push to prevent pushing _broken code_, but here it can't prevent anything on the pushed references…

Additionnaly, `CaptainHook\App\Hook\Condition\FileChanged\*` has 3 classes: `OfType`, `All`, `Any`, but only `OfType` is compatile with `pre-push`

**Comment by sebastianfeldmann** [comment]
> Additionnaly, `CaptainHook\App\Hook\Condition\FileChanged\*` has 3 classes: `OfType`, `All`, `Any`, but only `OfType` is compatile with `pre-push`

Yes, at the moment that is true, because getting a list of files changed works differently on pre-push, post-merge, post-checkout, and post-rewrite :)

I have to clean that up at some point :)

**Comment by sebastianfeldmann** [comment]
Oh looks like I did that, I just didn't update the `Restrictions`.

So after my next push `All` and `Any` should also work for `pre-push`.

**Comment by sebastianfeldmann** [comment]
Fixed with `5.15.4` docs updates as well ;)
