### ISSUE TITLE
LogicAnd condion does not allow to combine conditions per file

### ISSUE THREAD

**Issue by CircleCode** [captainhookphp/captainhook#206]
For example, I would like to run action if _a php file has been modified in dir `src/new/`_

The following example from the doc will be true if both conditions are validated
- **any file** has been modified in `src/new/`
- a php file has been modified **everywere**

```json
{
  "conditions": [
    {
      "exec": "and",
      "args": [{
        "exec": "\\CaptainHook\\App\\Hook\\Condition\\FileStaged\\InDirectory",
        "args": [
          ["src/new"]
        ]
      },{
        "exec": "\\CaptainHook\\App\\Hook\\Condition\\FileStaged\\OfType",
        "args": [
          ["php"]
        ]
      }]
    }
  ]
}
```

**Comment by sebastianfeldmann** [comment]
And that does not work?

**Comment by CircleCode** [comment]
> And that does not work?

That does work, but that allows only the condition “**any file** has been modified in `src/new/` AND a php file has been modified **everywere**” but not “**a php file** has been modified in `src/new/`”.

**Comment by sebastianfeldmann** [comment]
Ah got it

Yes creating a Condition that works like this looks like a good idea

```
{
  "conditions": [
    {
      "exec": "\\CaptainHook\\App\\Hook\\Condition\\FileStaged",
      "args": [{
        "inDirectory": "foo",
        "ofType": "php"
      }]
}
```

**Comment by sebastianfeldmann** [comment]
This is now fixed with the `FileStaged\ThatIs` condition :)
