### ISSUE TITLE
Support for Relative Path to CaptainHook Executable in Generated Hooks

### ISSUE THREAD

**Issue by RalfEggert** [captainhookphp/captainhook#219]
When installing CaptainHook through Phive, the generated hook scripts contain a direct absolute reference to the CaptainHook PHAR file, e.g., `/home/ralf/.phive/phars/captainhook-5.16.4.phar`. This approach causes problems in environments with multiple users or where users may have different home directories. It also creates complications when updating CaptainHook, as the scripts will still reference the old version even if the symbolic link in `./tools/captainhook` points to a newer one.

### Expected Behavior:

The generated hooks should use a relative path, e.g., `./tools/captainhook`, to reference the CaptainHook executable, allowing more flexibility, and ensuring that the correct version of CaptainHook is always called, regardless of the environment or user-specific configurations.

### Steps to Reproduce:

- Install CaptainHook via Phive: `phive install captainhook`
- Run `./tools/captainhook install`
- Examine the generated hook scripts in `.git/hooks/`

### Actual Result:

The generated hook scripts contain an absolute path to the CaptainHook PHAR file, such as `/home/ralf/.phive/phars/captainhook-5.16.4.phar`.

### Suggested Solution:

Modify the installation process to write the relative path, like `./tools/captainhook`, to the generated hook scripts instead of the absolute path to the PHAR file. Or allow a configured value in the `./captainhook.json` file. Adding `run-path` to the `config` did not work.

**Comment by sebastianfeldmann** [comment]
There is some magic in place checking if we should use relative or absolute path.
The current approach is: If the Cap'n is located within the git repository it will use a relative path. So you are able to move the directory around without any implications.
If the Cap'n is located outside of your repository I'm currently using an absolute path to archive the same result. Being able to move the source files around without any hassle.


```
    protected function getPathForHookTo(Directory $repo, Path $target): string
    {
        if (!$target->isChildOf($repo)) {
            return '\'' . $target->getPath() . '\'';
        }
        return '__DIR__ . \'/../../' . $target->getRelativePathFrom($repo) . '\'';
    }
```

I think you are using `PHIVE` with symlinks meaning PHP will not look at the symlink path, it will look at the `real_path` meaning the path to the real file. This is was `real_path` returns.

The config value `run-path` is currently only used in `Docker` mode.
I like the idea of using it to specify the executable to call and using it as given without any `real_path` magic.

A quick fix for you might be to copy the PHAR to `./tools/*`. Not perfect but then the path would be added relative.

```xml
<phar name="captainhook" version="^5.9" installed="5.9.1" location="./tools/captainhook" copy="true"/>
```

I will add check if the `run-path` value can be used as is and keep you updated here.

**Comment by sebastianfeldmann** [comment]
I think this already does it but I will improve the install tests a little bit more.
For now I don't have the best feeling not breaking something for somebody else.

**Comment by RalfEggert** [comment]
@sebastianfeldmann 

thanks for your thoughts and efforts so far.

Currently I use the following workaround. I have a small bash script anyway that installs all the necessary tools via phive. I have now extended this. We currently only use the pre-commit hook, so this fits for us.

```
echo "Run Captain Hook installation"
./tools/captainhook install --configuration=./captainhook.json pre-commit

echo ""
echo "Fix absolute path for Captain Hook in commit hook to local one"
HOOK_FILE=".git/hooks/pre-commit"

if [ -f "$HOOK_FILE" ]; then
  sed -i "s|$HOME/.phive/phars/captainhook-[0-9]*\.[0-9]*\.[0-9]*\.phar|./tools/captainhook|" "$HOOK_FILE"
  echo "The path in $HOOK_FILE was fixed."
else
  echo "Error: $HOOK_FILE does not exist."
fi
```

The workaround currently works in the team. But of course it would be great if the Cap'n also offers an official way to solve the problem.

**Comment by sebastianfeldmann** [comment]
You can use relative path now by configuring it in `run-cmd`  to overwrite the absolute path behavior.

Release with 5.17.0

**Comment by RalfEggert** [comment]
@sebastianfeldmann 

Almost 3 months later, I finally get around to trying it out and it works straight away. Thanks for your effort and work Captain Hook!

:+1:
