### ISSUE TITLE
Post-pull hook

### ISSUE THREAD

**Issue by cmmata** [CaptainHookPhp/captainhook#23]
Hello,

I would like to have a post-pull hook in my project, so every time I execute a `git pull` it could clear the local cache, execute other developers database migrations, or so. Do I make a PR? I think it should be more or less as #22.

**Comment by sebastianfeldmann** [comment]
I love the idea. Since `CaptainHook` it got a little bit more complicated to add new hook events.
You have to add 2 classes and change some unit tests to make it work.
I took the liberty to do it :)

Are you doing it for a specific framework?
I would love to add repositories like `captainhook/hooks-for-symfony`, `captainhook/hooks-for-magento`, `captainhook/hooks-for-laravel` or any other framework where this kind of actions would make sense.

Would you consider contributing to one of such repositories?

**Comment by sebastianfeldmann** [comment]
I've  just released version 4.0.1 including the new `post-merge` hook ;)

**Comment by sebastianfeldmann** [comment]
@heiglandreas maybe you or one of your colleagues is able to help with [captainhook/hooks-magento](https://github.com/CaptainHookPhp/hooks-magento)

**Comment by cmmata** [comment]
That was fast! Thank you :) I'll test it right now.

I'm planning to use it in several Symfony 3.4 / 4.X projects, so if you create a `hooks-for-symfony` repo or something like that, I'll try to contribute with some typical / officially recommended hooks.

**Comment by sebastianfeldmann** [comment]
No that's exactly what I was thinking of!
Provide a list of hooks that you can add to you `captainhook.json` file in a way that fit your needs.

**Comment by cmmata** [comment]
So it will be only a `captainhook.json` with some typical hooks to copy and paste to your own files? Okay, I'll be configuring our projects and then send a PR with the file.

**Comment by sebastianfeldmann** [comment]
The actual hook implementations that are specific to those frameworks should be in the "framework repositories" as well.

So for example if you want to trigger some Laravel artisan commands, the hook implementations triggering this commands should be in the `captainhook/hooks-laravel` repository.

So if people require `captainhook/hooks-laravel`  they can use those hooks in their `captainhook.json`

e.g.
composer.json
```json
"require-dev": {
    "captainhook/hooks-laravel": "^4"
  },
```
captainhook.json
```json
"post-merge": {
        "enabled": true,
        "actions": [
            {
                "action": "\\CaptainHook\\HooksLaravel\\Hook\\ClearCache",
                "options": {}
            }
        ]
    }
```

Or for any other framework we are supporting ;)

**Comment by cmmata** [comment]
I think there's an error.. If I execute this
```
  ➜ .git/hooks/post-merge 
```
The response is
```
  execute hook: pre-push
```
Looks like pre-push hook is executed instead of post-merge. It's because of this line https://github.com/CaptainHookPhp/captainhook/blob/a31842ddd0d0889e1b2989a2313aa74011430f58/src/Runner/Hook/PostMerge.php#L30

If I change this to `Hooks::POST_MERGE`, then post-merge hook is executed, but doesn't seem to execute the configured hooks and returns an error:
```
No arguments expected, got "0".
```

**Comment by sebastianfeldmann** [comment]
Oh man, epic copy paste fail incoming.
Should have executed this even once for real #sorry #fail #shame

Will release a fix ASAP

**Comment by sebastianfeldmann** [comment]
Fixed in version 4.0.2

**Comment by cmmata** [comment]
I tried to resolve it by myself, but I made the change to `App\Runner\Hook\PostMerge` instead of `App\Console\Command\Hook\PostMerge`. I didn't understand why it wasn't running.. Thanks for the fix! Now it's working. I'll be playing with several commands and post a json to the `hooks-symfony` repo.

**Comment by sebastianfeldmann** [comment]
The secret is that the `Symfony\Console\Commands` require you to specify all your arguments.
After doing so https://github.com/CaptainHookPhp/captainhook/blob/master/src/Console/Command/Hook/PostMerge.php#L41 it works like a charm

I made the decision to explicitly fail and force to create a separate command for each hook to make the original hook arguments like `isSquashMerge` available for every `CaptainHook\Action`
