### ISSUE TITLE
Support Symfony 7

### ISSUE THREAD

**Issue by alessandro-podo** [captainhookphp/captainhook#232]
i wanted to update my app to use Symfony7, but this Library use 3 Components with Symfony6.

Can i create a pull request for this? Or still someone working in this?

**Comment by sebastianfeldmann** [comment]
Sure feel free to open a pull request.
To avoid dependencies you could install `captainhook/captainhook-phar`  :)

**Comment by sebastianfeldmann** [comment]
Fixed with version 5.19.2 ;)
