### ISSUE TITLE
$CHANGED_FILES placeholder is empty for first push

### ISSUE THREAD

**Issue by Eydamos** [captainhookphp/captainhook#233]
For the first push you do to a remote the `CHANGED_FILES` placeholder is empty

Steps to reproduce:
* Clone a repository which has captainhook and a `pre-push` action which uses the `CHANGED_FILES` placeholder
* Create a new branch
* Make a commit
* Push your new branch to the remote

Current behaviour:
`$CHANGED_FILES` is empty

Expected behaviour:
`$CHANGED_FILES` list all changed files since the branch was created just like e.g. PhpStorm does when you push the changes

**Comment by sebastianfeldmann** [comment]
Fixed with version `5.20.0` 

Thanks for all the effort fixing this @Eydamos
