### ISSUE TITLE
Parameters passed to Git hook should be available in Action

### ISSUE THREAD

**Issue by shochdoerfer** [CaptainHookPhp/captainhook#24]
I might be wrong but I could not find a way to access the parameters passed to the Git hook itself. Like, I am currently trying to implement a pre-push hook and need to know the remote where the push will happen to. Does Captain Hook expose that information?

**Comment by sebastianfeldmann** [comment]
Now it does :)
At least for PHP actions.
Update to the latest version 4.0.3 and use `$io->getArguments()`

For the index names have a look at the hook console command
https://github.com/CaptainHookPhp/captainhook/blob/176b02d129e0881685f6193bc1166aec86bed61e/src/Console/Command/Hook/PrePush.php#L41

For binaries I have to create some search replace logic like 
`myPrePushCommand --target={$target}`
where I inject the original arguments upfront.

**Comment by shochdoerfer** [comment]
That was fast. Thanks man!

**Comment by sebastianfeldmann** [comment]
To be honest, I planned to do this for quite a while, I even thought it was already implemented when I read your message.
Original argument passing for binaries is coming up next

**Comment by sebastianfeldmann** [comment]
So I was half right, the binary part was the one that I already implemented.
If you want to pass original hook arguments to your binaries you can do so by using some `{PLACEHOLDER}`.

e.g.

    myPrePush.sh --target={TARGET} --url={URL}

The placeholders are listed in the formatCommand PHPDoc block. Currently they don't get escaped, still unsure if they should.

```php
    /**
     * Replace argument placeholder with their original values
     *
     * This replaces the hook argument placeholder.
     *  - prepare-commit-msg => FILE, MODE, HASH
     *  - commit-msg         => FILE
     *  - pre-push           => TARGET, URL
     *  - pre-commit         => -
     *
     * @param  string $command
     * @param  array  $args
     * @return string
     */
    protected function formatCommand(string $command, array $args) : string
    {
        foreach ($args as $key => $value) {
            $command = str_replace('{' . strtoupper($key) . '}', $value, $command);
        }
        return $command;
    }
```
