### ISSUE TITLE
Git LFS not working properly

### ISSUE THREAD

**Issue by Sm1lEE** [captainhookphp/captainhook#256]
Hi @sebastianfeldmann ,

we tried to use captainhook in combination with Git LFS in one of our projects.
In [this comment](https://github.com/captainhookphp/captainhook/issues/67#issuecomment-578262900) you suggest to move existing git-lfs-hooks with the `--move-existing-to` option to another directory and execute these original git lfs scripts via actions in captainhook's configuration file:
```json
{
   "pre-push": {
    "enabled": true,
    "actions": [
      {
        "action": "bin/hooks/pre-push {$TARGET} {$URL}"
      }
    ]
  }
}
```

In my tests, this did not work correctly. As written in the [git lfs pre-push documentation](https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-pre-push.adoc), in addition to both the `remote` and `remoteurl` arguments (mapped by captainhook to `TARGET` and `URL`), the `stdin` also has to be used. At least when using github, the file tracked by Git LFS would not be uploaded to the Git LFS storage.

Is there a way to provide the `stdin` to the action, e. g. `bin/hooks/pre-push {$TARGET} {$URL} {$STDIN}`? I did not find a way to access it in the configuration actions. Ultimately this should make it no longer necessary to use the `--move-to-existing` option and instead use the `stdin` placeholder in a standard action: `git lfs pre-push {$TARGET} {$URL} {$STDIN}`.

---

A quick solution for me was to write a custom action class, where the `stdin` is read and then provided to a custom `git lfs pre-push`-process:
```php
<?php

namespace App;

use CaptainHook\App\Config;
use CaptainHook\App\Console\IO;
use CaptainHook\App\Config\Action as ConfigAction;
use CaptainHook\App\Exception\ActionFailed;
use CaptainHook\App\Hook\Action;
use SebastianFeldmann\Git\Repository;
use Symfony\Component\Process\Exception\ProcessFailedException;
use Symfony\Component\Process\Process;

class MyAction implements Action
{
    public function execute(Config $config, IO $io, Repository $repository, ConfigAction $action): void
    {
        $arguments = $io->getArguments();
        if (!array_key_exists('target', $arguments)) {
            throw new ActionFailed('The `target` argument is missing.');
        }
        if (!array_key_exists('url', $arguments)) {
            throw new ActionFailed('The `url` argument is missing.');
        }

        $remoteName = $arguments['target'];
        $remoteUrl = $arguments['url'];

        $process = new Process(['git', 'lfs', 'pre-push', $remoteName, $remoteUrl]);
        $process->setInput(implode("\n", $io->getStandardInput()));

        try {
            $process->run();
        
            if (!$process->isSuccessful()) {
                throw new ProcessFailedException($process);
            }
        
            echo "Output:\n" . $process->getOutput();
        } catch (ProcessFailedException $e) {
            echo "The command failed with the following error:\n" . $e->getMessage();
        }
    }
}
```

**Comment by sebastianfeldmann** [comment]
Hi Stefan,

you are right since some hooks rely on `stdIn` it is a bit more complicated then just passing original arguments to the `git-lfs` hooks.

We would have to configure the `git-lfs` hooks like this

```
  "action": "echo {$STDIN} | hooks/lfs/pre-push {$ARGX} {$ARGY}"
```

For now `{$STDIN}` does not exist but that should be fixable ;)

**Comment by sebastianfeldmann** [comment]
5.23.5 has now a `{$STDIN}` placeholder :)

If you still have any issues with it feel free to reopen this at any time.

Thanks for making me aware of the problem ;)

**Comment by Sm1lEE** [comment]
Hi @sebastianfeldmann ,

your update works like a charm.
We can now easily use captainhook to handle all git hooks, including git-lfs. Thanks for your work!
