### ISSUE TITLE
Includes and docker mode

### ISSUE THREAD

**Issue by norgeindian** [captainhookphp/captainhook#261]
We would like to use a general captainhook config file for all our projects, which we then adapt in each project to the custom needs.
To do this, we would like to use the `includes` functionality and reference a file to specify specific settings.
As we are using docker in all our projects, we defined the following in the general config file:

```
{
    "config": {
        "run": {
            "mode": "docker"
        }
    },
``` 
In our project-specific file, which we include, we added the following:

```
{
    "config": {
        "run": {
            "exec": "docker exec -i project-xxx-php-fpm-1"
        }
    }
}
```

Both together should in my eyes have a complete configuration.
But when I run `vendor/bin/captainhook -f install`, I get the following error message:
` Run "exec" option missing for run-mode docker.`

As soon as I put the mode configuration in the project config file, it works. So the project-specific config file is correctly included. The other way round it works as well. It only does not work when both are separated.

Anyone an idea, how this could be solved?

**Comment by sebastianfeldmann** [comment]
The `config` part of an included configuration file will not be merged (security reasons).
otherwise you could overwrite the include level and other funky stuff from "remote".

The only way to overwrite the settings part in a `captainhook.json` is to use a local `captainhook.config.json` file right next to the local configuration.

**Comment by norgeindian** [comment]
Ah okay, I understand.
Thanks for the explanation, @sebastianfeldmann. That actually makes sense, I agree.

**Comment by norgeindian** [comment]
@sebastianfeldmann , the approach with `captainhook.config.json` now works perfectly for me. Thanks a lot for your help.

**Comment by norgeindian** [comment]
@sebastianfeldmann , sorry for bothering you again, but I just don't see what I'm doing wrong. In the last project, I worked with, I had the feeling, that it was solved, but now I tried again in another project and it happens again
:
This is my `captainhook.json`:

```
...
   "pre-push": {
        "enabled": true,
        "actions": [
            {
                "action": "composer run yireo",
                "options": [],
                "conditions": []
            }
        ]
    },...
```
(no config node)

This is my `captainhook.config.json`

```
{
    "config": {
        "run": {
            "mode": "docker",
            "exec": "docker exec -i project-php-fpm-1"
        }
    }
}
```

But the `composer run yireo` command is still run outside my docker container.
Do you have any idea, what I'm doing wrong?

**Comment by sebastianfeldmann** [comment]
Perfect right when I was typing the message 🤣

**Comment by sebastianfeldmann** [comment]
Thanks for the sponsoring @norgeindian. Greatly Appreciated ❤️

**Comment by norgeindian** [comment]
@sebastianfeldmann , one final question. Is it possible to add only one specific action in an included file to a specific hook?
So let's say, our `captainhook.json` includes the following action:

```
    "pre-push": {
        "enabled": true,
        "actions": [
            {
                "action": "action A",
                "options": [],
                "conditions": []
                    }
                ]
            }
```

Is there any way to add action B via an included file, so that in the end both actions a and b are run?
So having it like that in the included file?:

```
    "pre-push": {
        "enabled": true,
        "actions": [
            {
                "action": "action B",
                "options": [],
                "conditions": []
                    }
                ]
            }
```

or do I have to include both actions in my included local file, as the whole hook is merged?

**Comment by sebastianfeldmann** [comment]
Yes the `Actions` are merged together if that was your question.

If your local hook file contains `Loc1` `Loc2` actions and the included file contains `Inc1` and `Inc2`  for a hook the Cap'n will execute `Loc1`, `Loc2`, `Inc1` and `Inc2` I am not sure about the order though :)
