### ISSUE TITLE
Missing MatchesRegularExpression rule

### ISSUE THREAD

**Issue by mmenozzi** [CaptainHookPhp/captainhook#33]
Hi,
here https://captainhookphp.github.io/captainhook/extend.html is stated that:

> For example the regular expression validation is using a RuleBook with a single rule called MatchesRegularExpression.

But I'm not able to find this `MatchesRegularExpression` rule. I understand that I can use the `\CaptainHook\App\Hook\Message\Action\Regex` action but from what I see using the plain action is slightly different.

Indeed I'd like to validate commit messages against a regex but I don't want such validation on merge commits. From what I see here: https://github.com/CaptainHookPhp/captainhook/blob/f3f48a78549c8aad7095cbbb594cb520938d3010/src/Hook/Message/Action/Book.php#L55 the rule book already have this behavior. So I'd like to configure the `commit-msg` hook with something like that:
```json
"commit-msg": {
  "enabled": true,
  "actions": [
    {
      "action": "\\CaptainHook\\App\\Hook\\Message\\Action\\Rules",
      "options": [
        "\\CaptainHook\\App\\Hook\\Message\\Rule\\MatchesRegularExpression"
      ]
    }
  ]
```
But as I said there is no `MatchesRegularExpression` rule.

Should I provide a PR with that "missing" `MatchesRegularExpression` rule?

**Comment by sebastianfeldmann** [comment]
The problem with that is, that you can't pass arguments to `Rules` so you won't be able to pass the actual regex to validate against.

I think I will add the merging feature to the regex `Action` and an options that let you force the validation on merge commits as well.

**Comment by sebastianfeldmann** [comment]
I added there merge check to the regex action as well so now it should work as intended.
For now I don't think it makes any sense to validate merge commits as well.
So I'll wait for someone to actually request the feature to validate merge commits as well ;)

https://github.com/CaptainHookPhp/captainhook/blob/5d747ee5b0bf9f522bc9fb1075b62b66fe697866/src/Hook/Message/Action/Regex.php#L44-L48

**Comment by sebastianfeldmann** [comment]
Thanks for the feedback :)
