### ISSUE TITLE
How to hide the execute hook output from CaptainHook?

### ISSUE THREAD

**Issue by nntoan** [CaptainHookPhp/captainhook#53]
Hi there,

I'm wondering if anyone else feels the same but the following message is quite annoying to me

![Screenshot 2019-07-30 16 57 15](https://user-images.githubusercontent.com/3891429/62121386-b084d780-b2ed-11e9-9d49-83e2d0ba412e.png)

When I execute a git command, I know exactly what hook will be run after that, I also know what commands run because I can read `captainhook.json`.

Adding an option to `captainhook.json` to turn those messages off would be very helpful so the end-user can focus on the final output (in my case from GrumPHP) only.

Regards,
Toan

**Comment by sebastianfeldmann** [comment]
Maybe we can look into an option to reduce the output to a minimum

**Comment by heiglandreas** [comment]
Perhaps being abe to set `output` to `verbose` (current behaviour, default), `default` (only output from the commands,  no captainhook-output) and `quiet` (no outtput at all. Only the return Value will show success or no success)?

**Comment by sebastianfeldmann** [comment]
Since version 4.5.1 you can configure the CaptainHook verbosity

```javascript
{
  "config": {
    "verbosity": "normal"
  },
  ...
}
```

The default setting is currently `verbose` to be backwards compatible with the previous version.
I thing version 5 will make `normal` the expected default.
