### ISSUE TITLE
Add configuration for ANSI coloring

### ISSUE THREAD

**Issue by sebastianfeldmann** [CaptainHookPhp/captainhook#54]
Add possibility to enable and disable the terminal coloring.

**Comment by sebastianfeldmann** [comment]
With Version 4.4.2 you can now enable or disable ANSI colors for CaptainHooks output.
Do do so just add the `ansi-colors` config setting.

```javascript
{
  "config": {
    "ansi-colors": false
  }
  "pre-commit": {
    ...
  }
}
```

**Comment by sebastianfeldmann** [comment]
@ nntoan this is what you are looking for ;)

**Comment by nntoan** [comment]
Thank you so much 💯
