### ISSUE TITLE
PHPStan runs forever as pre-commit hook

### ISSUE THREAD

**Issue by iquito** [CaptainHookPhp/captainhook#58]
This might be similar to https://github.com/CaptainHookPhp/captainhook/issues/35, but I opened a new issue to be more specific:

I have a reasonably large codebase with lots of legacy code, and am using PHPStan and Psalm for new code while ignoring the issues in the older code. I usually run PHPStan via composer (so I can just type in `composer phpstan`) and that works fine.

I attempted a few times to add the exact same command I use via composer scripts as a pre-commit hook with CaptainHook, but it seems PHPStan crashes without CaptainHook noticing, as the PHPStan command just runs forever and never returns: via composer it runs for maybe 15-20 seconds, but even after waiting for 10 minutes or longer via CaptainHook nothing happens. This has been an issue ever since I adopted PHPStan for the project (about 6 months ago) and is still occuring with the latest PHP 7.3 version and the latest CaptainHook and PHPStan versions.

Why I report this here instead of with PHPStan is that it does work via composer scripts, which should work similarly as CaptainHook (with spawning another process, running it and then reporting back), and because CaptainHook just waits forever on PHPStan and there is no error message or hint what actually happened to PHPStan, so I actually wouldn't know what problem to report, where it occurs and why.

This problem does not occur with a new 6-month-old codebase, so there is something in this legacy project that leads to the problem. Ideally there would be a way to show the output from PHPStan while running CaptainHook, or maybe something that composer scripts does can be added to CaptainHook to overcome this.

**Comment by sebastianfeldmann** [comment]
I'll look into this. Maybe I provide you with some code you can use to debug it on your end.

**Comment by iquito** [comment]
Sure, that is probably the easiest option to narrow down the cause.

**Comment by sebastianfeldmann** [comment]
This maybe sounds strange but have you tried to put `composer phpstan` into the `captainhook` configuration?

**Comment by iquito** [comment]
An interesting idea: I tried it, and the same thing happens, so `composer phpstan` also never returns and the pre-commit hook waits forever.

I also tried running `vendor/captainhook/captainhook/captainhook-run pre-commit`, which seems to execute a hook outside of git and is ideal for testing this, but it also hangs. I also tried `php vendor/captainhook/captainhook/captainhook-run pre-commit`, with the same result.

So at least it should be something influenced by Captainhook, as this only happens when it is run through Captainhook, no matter how.

**Comment by sebastianfeldmann** [comment]
I updated the `cli` dependency and fixed an issue that could cause deadlocks.
Maybe that already fixes your issue

**Comment by iquito** [comment]
I upgraded (to sebastianfeldman/cli version 3.2.1), but still the same. Is there a way to output what PHPStan outputs when called via Captainhook? I guess that might be a sensible source to get a further hint.

**Comment by sebastianfeldmann** [comment]
Next try then :)
Update to `sebastianfeldmann/cli` 2.3.3.
Look for this file in your `vendor` folder.

    vendor/captainhook/captainhook/src/Runner/Action/Cli.php

And change the `Processor` to use in line 15 from `ProcOpen` to `Symfony`.

https://github.com/CaptainHookPhp/captainhook/blob/7b43019e273b91b4e3e0442437862459f692852b/src/Runner/Action/Cli.php#L15

```php
use SebastianFeldmann\Cli\Processor\Symfony as Processor;
```

If that solves your problem, the error is in my `ProcOpen` implementation.

**Comment by iquito** [comment]
That works! PHPStan and the pre-commit hook finish as expected with the Symfony processor.

**Comment by sebastianfeldmann** [comment]
Douh! Ok I will take a look at the Symfony implementation and see what I made differently :/

**Comment by ondrejmirtes** [comment]
I'm looking into this a little bit. @iquito What OS do you use where this problem occurs?

When looking at the ProcOpen implementation (https://github.com/sebastianfeldmann/cli/blob/master/src/Processor/ProcOpen.php) what's peculiar to me is that the code doesn't wait for the program to finish. It starts the process and immediately reads its output and closes the process. Also I don't think you can use `pipe` on Windows as the streams there are blocking.

I think at this point we'd be better off using Symfony's Process implementation or just use plain old `exec()` function (not sure how important is to have stdout and stderr strings in different variables).

**Comment by sebastianfeldmann** [comment]
Thanks @ondrejmirtes for having a detailed look at this.

I changed the ProcOpen implementation so it "waits" for the process to finish before fetching the output and exit codes.
Migrating to the Symfony implementation could be done quite quickly but for now I'm still a bit reluctant to add the Symfony dependency to CaptainHook just to prevent possible conflicts with users project dependencies.

@iquito could you give it another try?

**Comment by ondrejmirtes** [comment]
> I'm still a bit reluctant to add the Symfony dependency to CaptainHook

Yeah, that's why I separated `phpstan/phpstan` package from `phpstan/phpstan-src`. The first one is only a PHAR file and should be used by all users (it doesn't `require` anything in its composer.json), and the second one is development-only, and even cannot be requested as a Composer package. It's a great fit for tools like this that are not related to application source code (like an MVC framework).

I'm now free to add any dependency I want, and as a bonus, I now have a "build" step before publishing the package, so I'm free to do more stuff before building the final PHAR.

**Comment by dimitar-ivanov-tryzens** [comment]
Hi @sebastianfeldmann I've stumbled on the same issue I think, but using PHPCS.
Using Captainhook 5.1.1
I have project that has lots of errors detected with PHPCS something like 7 000 lines of output. Running PHPCS works ok, but when the action is triggered from a pre-push hook it will run very long with 100% cpu for that thread, no errors thrown. I was experimenting with this new project and thought that I broke something, but then I've noticed that if I lower the number of scanned directories from phpcs it will pass. Why I think it's connected with output? If I put in the hook not only `vendor/bin/phpcs`, but redirect the output to file like `vendor/bin/phpcs > errors.txt` all works fine. I've tested with php 7.3, 7.2, in Docker container and also on bare metal - the same result.
I've tested with a previous version that I have on an old project 4.5.8 it works fine.
I've tried your fix with the Symfony Processor and it works fine.
If there is something more I can help I'll be glad.
Thanks for the awesome soft.

**Comment by sebastianfeldmann** [comment]
I finally gave up and added the Symfony Process dependency. I caught myself copying over solutions for bugs in php from Symfony Process to my own implementation and realized that it doesn't make sense.

Instead why not just use Symfony Process. I will totally consider @ondrejmirtes solution to create a package only containing the PHAR file. So everybody just uses the PHAR even if composer is used to install the Cap'n. Until then we have to live with the extra dependency ;)

Sorry it took so long to just do the obvious thing.

You can install version 5.1.2 and everything should work again.
If you still have issues feel free to just reopen this issue.

Thanks for your feedback and your patience

**Comment by boesing** [comment]
@ondrejmirtes I'm curious if one could keep a single repository with all requirements (but the php requirement) in `require-dev` and excluding all sources, tests, e.g. as `archive.exclude` and `.gitattributes` and creating the `phar` file within a binary directory and adding this to the `bin` config of composer. github actions could create the phar and add it to the tag (never worked with actions yet but wondering if thats possible).

Did you tried that?

**Comment by dimitar-ivanov-tryzens** [comment]
I have tested 5.1.2 and it works fine for me.

**Comment by ondrejmirtes** [comment]
@boesing I wouldn't try combining the two. For one, in order to be consistent, you'd have to update the PHAR in every commit (and not forget about it).
