### ISSUE TITLE
Changes via captainhook binary removes "config" entry from captainhook.json

### ISSUE THREAD

**Issue by boesing** [CaptainHookPhp/captainhook#59]
Hey there,

using `vendor/bin/captainhook` to either `enable`, `disable` or `add` an action, the `\CaptainHook\App\Config\Util::writeToDisk` will only write the contents of `\CaptainHook\App\Config::getJsonData`.

This method only provides the configuration for known (valid) hooks but will drop the `config` section.

**Comment by sebastianfeldmann** [comment]
Thanks @boesing for reporting the issue ;)

I just released version 4.5.3 with a fix for this issue.
