### ISSUE TITLE
Wrong path to captainhook-run with run-mode: docker

### ISSUE THREAD

**Issue by jsor** [CaptainHookPhp/captainhook#61]
We're using `run-mode: docker` in our config and since v4.5.4, the hook scripts contain a wrong path to the `captainhook-run` binary.

Example `commit-msg`

```bash
#!/usr/bin/env bash
docker exec container ./absolute/path/to/vendor/bin/captainhook-run commit-msg "$@"
```

*(Note the leading dot before the absolute path).*

Before, it contained the correct relative path

```bash
#!/usr/bin/env bash
docker exec container ./vendor/bin/captainhook-run commit-msg "$@"
```

**Comment by sebastianfeldmann** [comment]
Should be fixed in version 4.5.6
Please give it a try

**Comment by jsor** [comment]
Looks like 4.5.6 still isn't avalailable on Packagist.

**Comment by sebastianfeldmann** [comment]
Somehow the packagist API wasn't responding, I triggered the update manually :)

Should be available now #sorry

**Comment by jsor** [comment]
Fix confirmed. Works again with 4.5.6, thanks! 👍

**Comment by sebastianfeldmann** [comment]
Thanks for reporting the issue and for the feedback 😊
