### ISSUE TITLE
Conditions should accept regexes or wildcards

### ISSUE THREAD

**Issue by shochdoerfer** [CaptainHookPhp/captainhook#66]
To make the pre-commit hooks faster when editing non php files, I'd love to execute CodeSniffer only when PHP files have been changed. The implemented conditions seem only to accept full filenames and no wildcards or regex expressions.

Any chance we could add support for this? Any pointers on how to tackle this? E.g. extend the current condition implementation or add separate condition classes?

**Comment by heiglandreas** [comment]
Best would probably to create a class `RegEx` similar to the [Any](https://github.com/CaptainHookPhp/captainhook/blob/master/src/Hook/Condition/FileChanged/Any.php)-Class which then matches the filename against the regex. Or `Glob` for glob-wildcards...

**Comment by sebastianfeldmann** [comment]
Or change any so it accepts regex or wildcard pattern. But I like the idea of creating separate ones.
`AnyThatMatchesRegex`
`AnyThatMatchesWildcard`
Not sure if we need both internally we will most probably convert wildcards to regex to check them.
Since the `IndexOperator` supports it we could easily do a.
`AnyOfType` and pass `php` or `js` to it.

**Comment by shochdoerfer** [comment]
Oh Captain my captain, I expected guidance and not some crazy thoughts :)

Basically I see 2 ways of going forward:
- Extend current Any/All implementation to make use of something like [fnmatch](https://www.php.net/manual/de/function.fnmatch.php) if that does not break the current logic
- Implement separate condition classes like `AnyOfType` & `AllOfType`

I'd love to go solution 1 and extend the current implementation. For my current use case `*OfType` conditions would be enough, but I am not sure how "useable" they are for other use cases. I would want to avoid adding those `AnyThat*` classes. I feel this will grow and grow over time and in the end no one has an overview of what implementations are there.

**Comment by sebastianfeldmann** [comment]
`fnmatch` sounds great!

So we could do something like this

```json
"conditions": [
          {
            "exec": "\\CaptainHook\\App\\Hook\\Condition\\FileChanged\\Any",
            "args": [
              ["src/Controller/*.php", "src/Service/*.php"]
            ]
          }
        ]
```

**Comment by shochdoerfer** [comment]
Will tackle this in the next week or so.
