### ISSUE TITLE
[Feature] Parallel execution of actions with symfony/process in a subprocess

### ISSUE THREAD

**Issue by boesing** [captainhookphp/captainhook#72]
I am having some hooks in my captainhook configuration.
Actually, every action takes for example X seconds which all are getting summed up to the execution time of the hook.

With asynchronous handling of actions, it would be possible to minimize the execution time of each hook to the maximum execution time of the slowest action.

Using `symfony/process` with a new console command `action` for example (which would execute a single action only) could run any action in a subprocess which could be asynchronously handled by the main hook command. 
After this, any action output (stderr, stdout) could be merged together and provided to the consumer.

This would even provide any failure and not just the first which failed. Therefore, any failure can be fixed at once instead of fixing one by one.

**Comment by heiglandreas** [comment]
I've renamed this to "Parallel execution" as from my understamding you want to call the different action in parallel and not asynchronous. Asynchronous in a git hook would mean "call the action but don't wait for it to complete and therefore don't bother about the return code...". Which is not what you want from my understanding

**Comment by boesing** [comment]
Yup, I want to run the actions in parallel. Ofc it is necessary to handle the exit codes.

**Comment by boesing** [comment]
Just as a sidenode:
There could be issues with tasks which manipulate contents of a file (e.g. cs-fixer).
If parallel tasks read/write the same file, there might be race-conditions.
*Probably* some tasks have to provide the information if they are read-only or read-write to internally orchestrate the parallel executions.

**Comment by sebastianfeldmann** [comment]
Good point
