### ISSUE TITLE
Discussion - Force PHAR usage via sub package

### ISSUE THREAD

**Issue by sebastianfeldmann** [captainhookphp/captainhook#84]
### Problem
Currently there are two ways to execute the Cap'n. The first is executing the PHP script installed via composer, the second one is via PHAR file. Both methods have some minor but significant differences that could lead to maintaining problems in the future.

### Possible solution
To get back to a single way of executing the Cap'n the idea is to transform the main `captainhook` composer package into a PHAR container package only containing the PHAR files and move the source code and all to a new `captainhook-app` repository. As an example you can see something similar in the [PHPStan](https://github.com/phpstan/phpstan) repository. 

### Pro
- Only one way of execution
- Easier to maintain
- Less bugs (hopefully)
- Never any version collisions because of the isolated scoped PHAR file (this is **HUGE**) 

### Contra
- Testing a `dev-master` state would get really complicated and will potentially stupidly increase the size of the PHAR container repository if we would commit a new PHAR for every push into the app repository.
- Not important but I personally do not like the idea of committing binary files to a repository :)

## Side effect
Doing this change would have a nice side effect. The main package could be converted into a composer plugin. This would make the handling of certain events easier (install/uninstall) and we could deprecate the `plugin-composer` package and always have the functionality build in from the get go.
If someone needs the pure variant without composer, they could always go for the PHAR only installation.

## Things to consider
A possible migration could be challenging. Older versions should still be installable so we would have to "leave"  the source code and all inside the main repository (at least in the git history) even if it is not needed there for the latest version. No biggy but then we would have 2 repositories with the full source code history until version 5 🤦 

The release process would get massively more complicated
- Push and tag app repository
- Build PHAR
- Copy PHAR to main repository
- Commit PHAR into main repository
- Tag main repository as well
- Create release for main repository with PHAR and signature file

I'm happy to get feedback on this idea.

**Comment by shochdoerfer** [comment]
Moving to phar-only distribution makes sense for a build/development tool, I guess.

Why not leave the current repo as is, remove the composer.json file for future versions to not allow composer installs any more, and push the .phar file to the plugin-composer repo? Thus one would only have to install the plugin-composer package via Composer to get the phar file and the glue code to hook into Composer?

If someone only wants the .phar file, then installing it via phive is still possible.

**Comment by heiglandreas** [comment]
I would leave the composer.json and mark is as deprecated and suggest installing the composer plugin. The whole process of building the PHAR could be automated and then the artifact is published with the tag in github. No need to push a binary file to the repo IMO...

**Comment by heiglandreas** [comment]
Though moving to including the PHAR would mean to manually update the phar on calling composer update... We can not necessarily relly on phive as it might not be installed.

**Comment by shochdoerfer** [comment]
@heiglandreas that's why I thought it might help to add the .phar file to the repo as well. So that when you update the `plugin-composer` package, it would update the .phar file as well.

I assume the `tooly-composer-script` package won't help us as it has to be used from within the root composer.json file, right?

**Comment by heiglandreas** [comment]
But instead of adding the Phar file itself we could add the path to the phar file. And then download it on-the-fly. Either way it would always link a specific version of The Cap'n to a specific version of the plugin. 

Having an algo that downloads the latest version of The Cap'n would allow us to update The Cap'n without having to update the plugin. At least within certain constraints... 

Adding that shouldn't be too tricky as the semver package is available already and the path to the tags of The Cap'n is also known. I build something lime that already for getlattestassets.com. Happy to add that know-how 😉

**Comment by shochdoerfer** [comment]
Sounds good to not need to update the plugin for each minor release of the core package.

**Comment by sebastianfeldmann** [comment]
I'm not sure if separating the Cap'n and composer update mechanics is a good idea. It makes it a thing on its own and another thing you have to take care of and think of.

If I understand it correctly PHPStan is automatically committing the PHAR file to the default `phpstan/phpstan` repo and references the PHAR as `bin` in the `composer.json`, nothing is done manually.

This way every time you update the package you get the right PHAR file. This would mean we do not have to implement special download and update logic ourself into the composer plugin.

This comes with all the drawbacks I mentioned, more difficult `dev-master` testing, binaries added to the git repo ...
Would be so nice to have PHAR installation in composer as well (other topic)

Before adding custom update logic to the package I think I would rather keep the two execution variants, because the effort of implementing the custom download and update logic would outweigh the 2 execution method maintaining :/

I think we can agree that committing PHAR files is a dirty workaround to handle composers shortcomings in terms of PHAR files.

The question is: 
Do the benefits outweigh the hackyness of the "solution".

**Comment by heiglandreas** [comment]
> Would be so nice to have PHAR installation in composer as well (other topic)

Talked about this some time ago to Jordi and the answer was quite clear: No

I then tried to create a plugin to handle that but – at least with the way composer was built at that time – it was not possible to remove the PHAR-package from the resolution graph without either modifying composer or doing very hacky stuff. So I stopped bothering.

Perhaps now with composer 2 it might be possible...

**Comment by shochdoerfer** [comment]
> This comes with all the drawbacks I mentioned, more difficult dev-master testing, binaries added to the git repo ...

That's why I thought to leave the `CaptainHookPhp/captainhook` untouched and commit the released .phar file to the `CaptainHookPhp/plugin-composer` repository and create a new release there. That way development of the core package be can done as is. 

But sure, we could also follow the Phpstan approach and create a new `CaptainHookPhp/captainhook-src` repo, do the main development there and push the .phar file to `CaptainHookPhp/captainhook` repo. On the plus side, existing users would not need to migrate. Ideally, they don't even realize that a change was done.

**Comment by heiglandreas** [comment]
I've build [a PR](https://github.com/CaptainHookPhp/plugin-composer/pull/8) illustrating the idea of downloading the latest asset matching a defined version constraint.

**Comment by theseer** [comment]
If there's anything that phive or phar.io can provide to help here, let us know.

It seems like there are more people interested in somehow having phive and composer be more closely collaborating. I'm not yet convinced I like that - they do serve totally different purposes after all - but I can see the "edge case" (from phive's perspective) of having tooling that needs additional code from a repository or have other depdenencies.

With Composer 2.0, maybe there's also a nice(r) hook (no pun intended ;) ) for adding a phive-plugin of some sort? We also considered to provide a library that enables others to leverage the power of phive without having a user to install it manually first...

**Comment by sebastianfeldmann** [comment]
I totally agree with you that tooling and dependencies are two completely different things. The problem is, that people got so used to the convenience of `Composer` even installing another tool like `phive` manually is too much for them. As consultant I think you can imagine what kind of discussions I have to participate in #facepalm.

As I'm thinking about this more and more I really getting a hang of the "solution" `phpstan`  implemented. It obviously is a hack to commit the `phar` to the repository, but it works :/

**Comment by theseer** [comment]
It's an ugly hack. There must be a nice(r) solution. Maybe we can brainstorm about it some time in a video chat session?

**Comment by heiglandreas** [comment]
[:point_up_2:](https://github.com/CaptainHookPhp/plugin-composer/pull/8) :shrug:

**Comment by sebastianfeldmann** [comment]
I really like Arnes idea of meeting via video session.
I would love to get together some people to share and organize my/our thoughts around this topic.
I created a doodle to find a date next week. Hope you will join ;)

https://doodle.com/poll/6n8ehf85h3qar35m

@heiglandreas @theseer @shochdoerfer 

/cc @icanhazstring

**Comment by icanhazstring** [comment]
Would love to take part. But mostly the time I take my kids to bed 😉

But I am traveling to Münster next week, so Wednesday a bit later would be nice, since I am arriving at 22 in Münster. Or earlier so I could attend while on the train.

**Comment by shochdoerfer** [comment]
Don't have too much time next week, sorry. Feel free to do the meeting without me if that makes it easier :)

**Comment by sebastianfeldmann** [comment]
Next major version of the Cap`n will be released as PHAR ;)
